#!/usr/bin/env python3


def main():
    import numpy as np
    import tensorflow as tf

    zero_out = tf.load_op_library("/tmp/zero_out.so").zero_out
    print(
        np.isclose(
            zero_out([[1, 2], [3, 4]]).numpy(),
            np.array([[1, 0], [0, 0]], dtype=np.int32),
        ).all()
    )
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
